version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-credentials:username"
    SECRET_PASSWORD: "pipeline-docker-credentials:password"

phases:
    pre_build:
      commands:
        - echo Logging in to Dockerhub
        - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin
    build:
      commands:
        - echo "Building Docker Image..."
        - docker build -t yahyamuxu/pottery-db:latest .
    
    post_build:
      commands:
        - echo "Pushing Docker Image..."
        - docker push yahyamuxu/pottery-db:latest
    

artifacts:
    files:
      - Dockerfile
